kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-Payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payroll
  template:
    metadata:
      labels:
        app: Payroll
    spec:
      containers:
        - name: Payroll
          image: Payroll-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
